import type { Metadata } from "next";
import "../globals.css";
import MaxWidthWrapper from "../components/MaxWidthWrapper";
import MainNavbar from "../components/MainNavbar";
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "../components/providers/auth-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
  <AuthProvider session={session}>
    <nav className='sticky h-16 inset-x-0 top-0 z-30 backdrop-blur-xl transition-all'>
      <MaxWidthWrapper>
        <MainNavbar />
      </MaxWidthWrapper>
    </nav>
    {children}
  </AuthProvider>
  );
}
