import type { Metadata } from "next";
import "../globals.css";
import MaxWidthWrapper from "../components/MaxWidthWrapper";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <>
  <nav className='sticky h-16 inset-x-0 top-0 z-30 backdrop-blur-xl transition-all'>
    <MaxWidthWrapper>
            <div className='flex h-14 items-center justify-between border-zinc-200 shadow-sm'>
              <div className='flex items-center gap-2 mt-'>
                <Link href="/" className="flex z-40 font-extrabold text-3xl text-blue-400 italic font-sans">
                <Image src="/images/logo_1.jpg" width={150} height={400} alt='logo'/>
                </Link>
              </div>

            {/* todo: add mobile nav function*/}
            <div className='hidden items-end space-x-2 sm:flex text-zinc-700 justify-between'>
                <Link href="/dashboard" className='px-4 py-2 border-b-2 hover:border-blue-500 border-blue-300 font-bold rounded-sm shadow-sm'>Dashboard</Link>
                <Link href="/" className='px-4 py-2 border-b-2 hover:border-blue-500 border-blue-300 rounded-sm shadow-sm text-zinc-500'>Pricing</Link>
            </div>
            </div>
    </MaxWidthWrapper>
  </nav>
  {children}
  </>
  );
}
